#!/bin/bash

get_var()
{
  tmux display-message -p "#{$1}"
}

if [ $(get_var "pane_right") -eq $(( $(get_var "window_width") - 1 )) ]; then
  cursor_y=$(get_var "cursor_y")
  if ! tmux next-window ; then
    tmux select-pane -R
    exit 0
  fi
  [ $(get_var "window_zoomed_flag") -eq 1 ] && exit 0
  exit 0
  # curr=0
  # while tmux select-pane -t $(( curr++ )); do
  #   [ $(get_var "pane_bottom") -ge $cursor_y ] &&
  #     break
  # done
else
  tmux select-pane -R
fi

