#!/bin/bash

get_var()
{
  tmux display-message -p "#{$1}"
}

if [ $(get_var "pane_left") -eq 0 ]; then
  cursor_y=$(get_var "cursor_y")
  if ! tmux previous-window ; then
    tmux select-pane -L
    exit 0
  fi
  [ $(get_var "window_zoomed_flag") -eq 1 ] && exit 0
  exit 0
  # curr=$(tmux list-panes | wc -l)
  # while tmux select-pane -t $(( --curr )); do
  #   [ $(get_var "pane_right") -eq $(( $(get_var "window_width") - 1 )) ] &&
  #     [ $(get_var "pane_top") -le $cursor_y ] &&
  #     break
  #   [ $curr -eq 0 ] &&
  #     break
  # done
else
  tmux select-pane -L
fi

