#!/bin/bash

n1=$(echo "$1" | sed -r 's/(\.0+)+$//' | sed -r 's/(\.|^)0+([0-9]+)/\1\2/g')
n2=$(echo "$2" | sed -r 's/(\.0+)+$//' | sed -r 's/(\.|^)0+([0-9]+)/\1\2/g')

[[ "$n1" == "$(echo -e "$n1\n$n2" | sort -V | head -n1)" ]]

